WidgetMetadata={id:"hyj1817.hentaimama.home",title:"Hentaimama",icon:"https://hentaimama.io/wp-content/themes/dooplay/assets/img/favicon.png",version:"1.1.0",requiredVersion:"0.0.2",description:"Hentaimama 首页、详情与 HLS 播放",author:"Forward Widgets",site:"https://hentaimama.io",modules:[{id:"latest",title:"最新发布",functionName:"loadLatest",cacheDuration:600,params:[]},{id:"series",title:"Hentai 系列",functionName:"loadSeries",cacheDuration:600,params:[]},{id:"uncensored",title:"无码",functionName:"loadUncensored",cacheDuration:600,params:[]}],search:{title:"搜索",functionName:"search",params:[{name:"keyword",title:"关键词",type:"input"}]}};
var B="https://hentaimama.io",U="Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1";
function clean(s){return String(s||"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#039;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim()}
function full(s){s=String(s||"");return s.indexOf("http")===0?s:B+"/"+s.replace(/^\//,"")}
async function page(u,ref){var r=await Widget.http.get(full(u),{headers:{"User-Agent":U,Referer:ref||B+"/"},timeout:15000});return typeof r.data==="string"?r.data:r.body||""}
function cards(h){var $=Widget.html.load(h),a=[];$("a[href]").each(function(){var q=$(this),u=q.attr("href")||"",im=q.find("img").first(),cover=im.attr("data-src")||im.attr("src")||"",t=im.attr("alt")||q.attr("title")||clean(q.text());if(u.indexOf("/tvshows/")<0||!cover||!t||a.some(function(x){return x.link===u}))return;u=full(u);a.push({id:"hentaimama:"+u.replace(B+"/",""),type:"url",title:t,seriesName:t,description:t,posterPath:cover,backdropPath:cover,mediaType:"tv",link:"hentaimama:"+u})});return a}
async function list(u){try{return cards(await page(u))}catch(e){return[]}}
async function loadLatest(){return list(B+"/")}async function loadSeries(){return list(B+"/hentai-series/")}async function loadUncensored(){return list(B+"/genre/uncensored/")}async function search(p){return list(B+"/?s="+encodeURIComponent(p&&p.keyword||""))}
function streamFromHtml(h,ref){var m=String(h||"").match(/dt_embed=hls[^>]*[?&]p=([^&"']+)/i);if(!m){var f=String(h||"").match(/<iframe[^>]+src=["']([^"']*dt_embed=hls[^"']*)["']/i);if(f)m=f[1].match(/[?&]p=([^&]+)/i)}if(!m)return "";var p=decodeURIComponent(m[1]);try{p=atob(p)}catch(e){}return full(p)}
async function loadDetail(link){var u=String(link||"").replace(/^hentaimama:/i,"");u=full(u);try{var h=await page(u),$=Widget.html.load(h),title=$("h1").first().text().trim()||clean($("title").text()).replace(/\s+-\s*Hentaimama.*$/i,"")||u,cover=$("meta[property='og:image']").attr("content")||$(".poster img").first().attr("src")||"",eps=[];$("a[href]").each(function(){var a=$(this),href=a.attr("href")||"";if(href.indexOf("/episodes/")<0||eps.some(function(x){return x.href===href}))return;eps.push({href:full(href),name:clean(a.text())||"Episode "+(eps.length+1)})});if(!eps.length)eps=[{href:u,name:"播放"}];var out=[];for(var i=0;i<eps.length;i++){try{var eh=await page(eps[i].href,u),url=streamFromHtml(eh,eps[i].href);if(url)out.push({id:"hentaimama:"+eps[i].href.replace(B+"/",""),type:"detail",title:eps[i].name,seriesName:title,episodeName:eps[i].name,episode:i+1,description:title,posterPath:cover,backdropPath:cover,mediaType:"tv",videoUrl:url,playerType:"app",customHeaders:{"User-Agent":U,Referer:eps[i].href},headers:{"User-Agent":U,Referer:eps[i].href},link:"hentaimama:"+eps[i].href})}catch(e){}}if(out.length===1)return out[0];return {id:"hentaimama:"+u.replace(B+"/",""),type:"detail",title:title,seriesName:title,description:title,posterPath:cover,backdropPath:cover,mediaType:"tv",link:"hentaimama:"+u,episodeItems:out};}catch(e){return {id:"hentaimama:"+u,type:"detail",title:u,link:"hentaimama:"+u}}}
