/* Generated by scripts/build-maccms.js from lib/maccms.js. Do not edit directly. */
/* 苹果CMS 聚合播放源 · 入口层
 * 本文件不单独使用，由 scripts/build-maccms.js 与 lib/maccms.js 拼接后
 * 生成 widgets/maccms-source.js。修改请改这里，不要改生成物。
 */

var DEFAULT_SITES = '金鹰资源,https://jyzyapi.com/api.php/provide/vod/';

WidgetMetadata = {
  id: 'hyj1817.maccms.resource',
  title: '苹果CMS 聚合源',
  icon: 'https://jyzyapi.com/favicon.ico',
  version: '1.0.0',
  requiredVersion: '0.0.1',
  description: '苹果CMS/MacCMS 通用聚合播放源：多站可配、自动翻页、片名归一化匹配、解析型线路可选',
  author: 'HYJ1817',
  site: 'https://github.com/HYJ1817/fw-modules',
  globalParams: [
    {
      name: 'multiSource',
      title: '是否启用聚合搜索',
      type: 'enumeration',
      value: 'enabled',
      enumOptions: [
        { title: '启用', value: 'enabled' },
        { title: '禁用', value: 'disabled' }
      ]
    },
    {
      name: 'sites',
      title: '资源站列表',
      type: 'input',
      value: '',
      description: '每行一条：名称,接口地址。留空使用内置站点。'
    },
    {
      name: 'maxPages',
      title: '每站最多搜索页数',
      type: 'count',
      value: 5,
      description: '精确片名常不在第 1 页；页数越大越慢。'
    },
    {
      name: 'strictSeason',
      title: '严格季匹配',
      type: 'enumeration',
      value: 'off',
      enumOptions: [
        { title: '关闭（推荐）', value: 'off' },
        { title: '开启', value: 'on' }
      ]
    },
    {
      name: 'parseApi',
      title: '解析接口（可选）',
      type: 'input',
      value: '',
      description: '填写后解析型线路会经该接口转换；支持 {url} 占位符。留空则只返回直链。'
    }
  ],
  modules: [
    {
      id: 'loadResource',
      title: '加载资源',
      functionName: 'loadResource',
      type: 'stream',
      cacheDuration: 0,
      params: []
    }
  ]
};

async function loadResource(params) {
  return Maccms.loadResources(params || {}, {
    defaultSites: DEFAULT_SITES,
    keyPrefix: 'hyj1817_maccms',
    onError: function (site, error) {
      console.log('FW maccms: ' + site.title + ' 请求失败 - ' + ((error && error.message) || error));
    }
  });
}

/**
 * 苹果CMS / MacCMS V10 采集接口适配层
 * ===========================================================================
 * 这是一个「源码片段」，不是独立的 Forward 组件。它被 scripts/build-maccms.js
 * 内联进各个播放源组件中 —— Forward 的组件是单文件脚本，没有模块系统，
 * 因此共享逻辑只能靠构建期内联。
 *
 * 接口约定（苹果CMS V10 通用，非某一站点私有）：
 *   GET {api}?ac=detail&wd={关键词}&pg={页码}
 *   → { code, msg, page, pagecount, limit, total, list: [ { vod_name,
 *       vod_play_from, vod_play_url, vod_remarks, ... } ] }
 *
 * 三个必须记住的坑：
 *   1. 响应头恒为 Content-Type: text/html;charset=utf-8，即使正文是 JSON。
 *      宿主不会自动解析，必须自己做 typeof data === "string" 判断。
 *   2. 每页固定 20 条，limit 参数被忽略，翻页只能用 pg。
 *   3. h=（精确搜索）多数站点不支持，会被忽略并返回全量列表，不能依赖。
 *
 * 线路字段格式：
 *   vod_play_from = "线路A$$$线路B"          // $$$ 分隔线路
 *   vod_play_url  = "第01集$url#第02集$url$$$正片$url"   // # 分隔集，# 内 $ 分隔名与地址
 *
 * 本层不做任何站点私有逻辑，新增源站只需在 sites 里填域名。
 */

var Maccms = (function () {
  var DEFAULT_UA =
    'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1';

  var CN_NUM = { 一: 1, 二: 2, 三: 3, 四: 4, 五: 5, 六: 6, 七: 7, 八: 8, 九: 9, 十: 10 };

  var PUNCT = /[\s·・:：\-–—_.,，。!！?？'"“”‘’()（）[\]【】<>《》/\\|~^+*=&#@$%]/g;
  var ZERO_WIDTH = /[\u200b-\u200d\ufeff]/g;

  // -------------------------------------------------------------------------
  // 基础工具
  // -------------------------------------------------------------------------

  /**
   * 统一宿主返回：可能是已解析对象，也可能是原始字符串。
   * 这是本层存在的首要原因 —— 苹果CMS 的响应头永远不会是 application/json。
   */
  function unwrap(response) {
    if (!response) return null;
    var data = response.data !== undefined ? response.data : response;
    if (typeof data === 'string') {
      var text = data.trim();
      if (!text) return null;
      try {
        return JSON.parse(text);
      } catch (error) {
        return null;
      }
    }
    return data || null;
  }

  /** 手动拼查询串，不依赖宿主对 options.params 的支持。 */
  function buildUrl(base, query) {
    var pairs = [];
    for (var key in query) {
      if (!Object.prototype.hasOwnProperty.call(query, key)) continue;
      var value = query[key];
      if (value === undefined || value === null || value === '') continue;
      pairs.push(encodeURIComponent(key) + '=' + encodeURIComponent(String(value)));
    }
    if (!pairs.length) return base;
    return base + (base.indexOf('?') >= 0 ? '&' : '?') + pairs.join('&');
  }

  /**
   * 诊断日志。返回空列表时最需要它 —— 常见原因是宿主没有传片名，
   * 此时任何依赖片名搜索的播放源都会静默返回空。
   */
  function trace(payload) {
    try {
      console.log('FW_MACCMS ' + JSON.stringify(payload));
    } catch (error) {
      /* 日志失败不影响返回 */
    }
  }

  /** 去掉零宽字符、标点、空白与大小写差异，用于跨站片名比较。 */
  function normalize(value) {
    return String(value === undefined || value === null ? '' : value)
      .replace(ZERO_WIDTH, '')
      .toLowerCase()
      .replace(PUNCT, '');
  }

  function clean(value) {
    return String(value === undefined || value === null ? '' : value).replace(ZERO_WIDTH, '').trim();
  }

  // -------------------------------------------------------------------------
  // 片名解析
  // -------------------------------------------------------------------------

  /**
   * 拆出季号与主名。
   * 注意：结尾数字只把 1~2 位当季号，且该数字前必须是非数字字符 ——
   * 否则「狂飙1998」会被拆成主名「狂飙」（4 位年份被当季号），
   * 与真正要查的「狂飙」撞车，产生误匹配。
   */
  function parseSeason(rawName) {
    var name = clean(rawName);
    if (!name) return { base: '', season: 1 };

    var match = name.match(/第\s*([一二三四五六七八九十\d]+)\s*[季部]/);
    if (match) {
      var token = match[1];
      var number = /^\d+$/.test(token) ? parseInt(token, 10) : CN_NUM[token] || 1;
      return { base: clean(name.replace(match[0], '')), season: number || 1 };
    }

    // (.*[^\d]) 保证结尾的 1~2 位数字前面不是数字，从而拒绝 3 位以上的数字串
    match = name.match(/^(.*[^\d])\s*(\d{1,2})\s*$/);
    if (match) {
      return { base: match[1].trim(), season: parseInt(match[2], 10) || 1 };
    }

    return { base: name, season: 1 };
  }

  /** 集数解析：第01集 / 第1集 / 第1话 / EP01 / 纯数字。 */
  function parseEpisode(rawName, fallbackIndex) {
    var text = String(rawName === undefined || rawName === null ? '' : rawName);
    var match = text.match(/第\s*(\d+)\s*[集话回期]/);
    if (match) return parseInt(match[1], 10);
    match = text.match(/\b(?:ep|episode|e)\s*\.?\s*(\d+)\b/i);
    if (match) return parseInt(match[1], 10);
    match = text.match(/(\d+)/);
    if (match) return parseInt(match[1], 10);
    return fallbackIndex === undefined ? null : fallbackIndex;
  }

  /** 是否为可直接播放的地址（而非需二次解析的网页）。 */
  function isDirectStream(url) {
    var value = String(url || '').toLowerCase();
    if (!/^https?:\/\//.test(value)) return false;
    return /\.(m3u8|mp4|flv|ts)(\?|#|$)/.test(value) || /\/index\.m3u8/.test(value);
  }

  // -------------------------------------------------------------------------
  // 站点配置
  // -------------------------------------------------------------------------

  /**
   * 解析站点配置。支持两种写法：
   *   文本行  "名称,https://域名/api.php/provide/vod/"
   *   JSON    [{ "title": "名称", "url": "https://..." }]
   * 留空时使用 fallbackText。
   */
  function parseSites(raw, fallbackText) {
    var text = String(raw === undefined || raw === null ? '' : raw).trim();
    if (!text) text = String(fallbackText || '').trim();
    if (!text) return [];

    if (text.charAt(0) === '[' || text.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(text);
        var array = Array.isArray(parsed) ? parsed : parsed.sites || [];
        return array
          .map(function (item) {
            return { title: clean(item.title || item.name), value: clean(item.url || item.value || item.api) };
          })
          .filter(function (item) {
            return item.title && /^https?:\/\//.test(item.value);
          });
      } catch (error) {
        return [];
      }
    }

    return text
      .split('\n')
      .map(function (line) {
        var parts = String(line).split(',');
        if (parts.length < 2) return null;
        var title = clean(parts[0]);
        var value = clean(parts.slice(1).join(','));
        if (!title || !/^https?:\/\//.test(value)) return null;
        return { title: title, value: value };
      })
      .filter(Boolean);
  }

  // -------------------------------------------------------------------------
  // 入参兼容
  // -------------------------------------------------------------------------

  /**
   * Forward 的 loadResource 官方入参只有
   * tmdbId / imdbId / id / type / season / episode / link / videoUrl，
   * 并不含 seriesName —— 那是社区扩展。所以必须多键兜底。
   */
  function readTitle(params) {
    var keys = ['seriesName', 'title', 'name', 'videoName', 'vodName', 'seriesTitle'];
    for (var i = 0; i < keys.length; i++) {
      var value = clean(params[keys[i]]);
      if (value) return value;
    }
    return '';
  }

  function readType(params) {
    var value = String(params.type || '').toLowerCase();
    if (value === 'movie' || value === 'film') return 'movie';
    if (value === 'tv' || value === 'series' || value === 'episode') return 'tv';
    // 未提供时按「有集数信息即剧集」推断
    return params.episode || params.season ? 'tv' : 'movie';
  }

  // -------------------------------------------------------------------------
  // 匹配打分
  // -------------------------------------------------------------------------

  /**
   * 三档打分：
   *   300 全名一致（归一化后）
   *   200 主名一致且季号一致
   *   150 主名一致但季号不同
   *    60 包含关系（模糊，仅前两档落空时才可能被选中）
   *    -1 无关
   */
  function scoreTitle(itemName, wanted) {
    var info = parseSeason(itemName);
    var itemBase = normalize(info.base);
    var itemFull = normalize(itemName);
    var wantBase = normalize(wanted.base);
    var wantFull = normalize(wanted.raw);

    if (!itemBase || !wantBase) return -1;
    if (itemFull === wantFull) return 300;
    if (itemBase === wantBase) return info.season === wanted.season ? 200 : 150;
    if (itemBase.indexOf(wantBase) >= 0 || wantBase.indexOf(itemBase) >= 0) return 60;
    return -1;
  }

  function matchQuality(score) {
    if (score >= 200) return 'exact';
    if (score >= 150) return 'base';
    return 'fuzzy';
  }

  // -------------------------------------------------------------------------
  // 线路提取
  // -------------------------------------------------------------------------

  /** 把 vod_play_from / vod_play_url 拆成扁平的线路列表。 */
  function collectLines(item) {
    var playUrl = String(item.vod_play_url || '').replace(/#+$/, '');
    if (!playUrl) return [];

    var froms = String(item.vod_play_from || '').split('$$$');
    var blocks = playUrl.split('$$$');
    var lines = [];

    for (var i = 0; i < blocks.length; i++) {
      var sourceName = clean(froms[i]) || '线路' + (i + 1);
      var chunks = blocks[i].split('#');
      for (var j = 0; j < chunks.length; j++) {
        var parts = chunks[j].split('$');
        if (parts.length < 2) continue;
        var label = clean(parts[0]);
        var url = clean(parts.slice(1).join('$'));
        if (!url) continue;
        lines.push({ sourceName: sourceName, label: label, url: url });
      }
    }
    return lines;
  }

  /** 把一条线路转成 Forward 的 VideoResource。解析型线路需配置 parseApi 才会返回。 */
  function toResource(line, siteTitle, seriesTitle, episode, parseApi, quality) {
    var direct = isDirectStream(line.url);
    var finalUrl = line.url;
    var suffix = '';

    if (!direct) {
      if (!parseApi) return null;
      finalUrl =
        parseApi.indexOf('{url}') >= 0
          ? parseApi.replace('{url}', encodeURIComponent(line.url))
          : buildUrl(parseApi, { url: line.url });
      suffix = ' · 解析';
    }

    var nameParts = [siteTitle, line.sourceName];
    if (episode !== null && episode !== undefined) nameParts.push('第' + episode + '集');

    var descParts = [seriesTitle || line.label];
    if (line.label && line.label !== seriesTitle) descParts.push(line.label);
    descParts.push(direct ? (finalUrl.indexOf('.mp4') >= 0 ? 'MP4 直链' : 'HLS 直链') : '解析线路');
    if (quality === 'fuzzy') descParts.push('模糊匹配');

    return {
      name: nameParts.join(' · ') + suffix,
      description: descParts.join(' - '),
      url: finalUrl,
      customHeaders: { 'User-Agent': DEFAULT_UA },
      playerType: 'app',
    };
  }

  function dedupe(resources) {
    var seen = {};
    var output = [];
    for (var i = 0; i < resources.length; i++) {
      var resource = resources[i];
      if (!resource || !resource.url || seen[resource.url]) continue;
      seen[resource.url] = true;
      output.push(resource);
    }
    return output;
  }

  function filterByEpisode(resources, wantedEpisode, type) {
    if (type !== 'tv' || wantedEpisode === null || wantedEpisode === undefined) return resources;

    var matched = resources.filter(function (resource) {
      return resource._ep === wantedEpisode;
    });
    if (matched.length) return matched;

    // 集号对不上时兜底：请求第 1 集但源站首集编号不为 1，返回现有首集而非空列表。
    if (wantedEpisode === 1 && resources.length) {
      var firstEpisode = resources[0]._ep;
      if (firstEpisode !== null && firstEpisode !== undefined) {
        return resources.filter(function (resource) {
          return resource._ep === firstEpisode;
        });
      }
    }
    return matched;
  }

  // -------------------------------------------------------------------------
  // 网络
  // -------------------------------------------------------------------------

  async function fetchPage(site, keyword, page, options) {
    var url = buildUrl(site.value, { ac: 'detail', wd: keyword, pg: page });
    var response = await Widget.http.get(url, {
      headers: { 'User-Agent': DEFAULT_UA, Accept: 'application/json,text/plain,*/*' },
      timeout: (options && options.timeout) || 10000,
    });
    var body = unwrap(response);
    if (!body || !Array.isArray(body.list)) return { list: [], pagecount: 1, total: 0 };
    return {
      list: body.list,
      pagecount: parseInt(body.pagecount, 10) || 1,
      total: parseInt(body.total, 10) || 0,
    };
  }

  /**
   * 翻页搜索；命中全名一致的条目即提前停止，避免多余请求。
   * 单页失败不丢弃已取回的结果，但会通过 options.onError 上报，供诊断模块使用。
   */
  async function search(site, keyword, maxPages, wanted, options) {
    options = options || {};
    var collected = [];
    for (var page = 1; page <= maxPages; page++) {
      var result;
      try {
        result = await fetchPage(site, keyword, page, options);
      } catch (error) {
        if (typeof options.onError === 'function') options.onError(site, error, page);
        break;
      }
      if (!result.list.length) break;
      collected = collected.concat(result.list);

      if (wanted) {
        for (var i = 0; i < result.list.length; i++) {
          if (scoreTitle(result.list[i].vod_name, wanted) >= 300) return collected;
        }
      }
      if (page >= result.pagecount) break;
    }
    return collected;
  }

  /** 在候选条目中挑出得分最高者。 */
  function pickBest(items, wanted) {
    var best = null;
    var bestScore = 0;
    for (var i = 0; i < items.length; i++) {
      var score = scoreTitle(items[i].vod_name, wanted);
      if (score > bestScore) {
        bestScore = score;
        best = items[i];
      }
    }
    if (!best) return null;
    return { item: best, score: bestScore, quality: matchQuality(bestScore) };
  }

  /** 把一条命中条目转成资源列表（含集号标记，供缓存后二次过滤）。 */
  function resourcesFromItem(item, siteTitle, seriesTitle, type, parseApi, quality) {
    var lines = collectLines(item);
    var output = [];
    for (var i = 0; i < lines.length; i++) {
      var episode = type === 'tv' ? parseEpisode(lines[i].label, i + 1) : null;
      var resource = toResource(lines[i], siteTitle, item.vod_name || seriesTitle, episode, parseApi, quality);
      if (resource) {
        resource._ep = episode;
        output.push(resource);
      }
    }
    return output;
  }

  // -------------------------------------------------------------------------
  // 主入口
  // -------------------------------------------------------------------------

  /**
   * 通用播放源解析。
   * @param {object} params  Forward 传给 loadResource 的入参
   * @param {object} options
   *   defaultSites  {string}  内置站点（文本行或 JSON），params.sites 为空时使用
   *   keyPrefix     {string}  缓存命名空间前缀
   *   onError       {function(site, error)}  单站失败回调，用于诊断
   * @returns {Promise<Array>} VideoResource[]
   */
  async function loadResources(params, options) {
    params = params || {};
    options = options || {};

    var paramKeys = [];
    for (var key in params) {
      if (Object.prototype.hasOwnProperty.call(params, key)) paramKeys.push(key);
    }

    // 默认放行：只有显式 disabled 才关闭。绝不能写成 !== "enabled"。
    if (String(params.multiSource || '').toLowerCase() === 'disabled') {
      trace({ event: 'skipped', reason: 'multiSource=disabled' });
      return [];
    }

    var seriesTitle = readTitle(params);
    if (!seriesTitle) {
      // 这是「线路列表为空」最常见的原因：Forward 未传任何片名字段。
      trace({
        event: 'no-title',
        at: new Date().toISOString(),
        paramKeys: paramKeys,
        note: '未收到片名，无法搜索。请确认宿主是否传递了 seriesName/title/name 之一。'
      });
      return [];
    }

    var type = readType(params);
    var parsed = parseSeason(seriesTitle);
    var wanted = {
      raw: seriesTitle,
      base: parsed.base || seriesTitle,
      season: parseInt(params.season, 10) || parsed.season,
      strictSeason: String(params.strictSeason || 'off').toLowerCase() === 'on',
    };

    var wantedEpisode = type === 'tv' ? parseEpisode(params.episode, parseInt(params.episode, 10) || 1) : null;

    var sites = parseSites(params.sites, options.defaultSites);
    if (!sites.length) return [];

    var maxPages = parseInt(params.maxPages, 10);
    if (!maxPages || maxPages < 1) maxPages = 5;
    if (maxPages > 10) maxPages = 10;

    var parseApi = clean(params.parseApi);
    var prefix = options.keyPrefix || 'maccms';
    var cacheKey =
      prefix +
      '_' +
      normalize(seriesTitle) +
      '_s' +
      wanted.season +
      '_' +
      type +
      '_' +
      (wanted.strictSeason ? 'strict' : 'loose');

    try {
      var cached = Widget.storage.get(cacheKey);
      if (cached && Array.isArray(cached) && cached.length) {
        return filterByEpisode(cached, wantedEpisode, type);
      }
    } catch (error) {
      /* 缓存不可用则继续走网络 */
    }

    var tasks = sites.map(async function (site) {
      // search 内部已通过 onError 上报网络层错误；这里只兜底解析层异常，避免重复上报。
      var reported = false;
      var report = function (error) {
        if (reported) return;
        reported = true;
        if (typeof options.onError === 'function') options.onError(site, error);
      };

      try {
        var items = await search(site, wanted.base, maxPages, wanted, {
          timeout: options.timeout,
          onError: function (failedSite, error) {
            report(error);
          },
        });
        var best = pickBest(items, wanted);
        if (!best) {
          trace({
            event: 'no-match',
            site: site.title,
            keyword: wanted.base,
            candidates: items.length,
            note: '该站返回了结果但没有任何条目与片名相关。'
          });
          return [];
        }
        if (wanted.strictSeason && best.quality !== 'exact') {
          trace({ event: 'rejected-strict-season', site: site.title, matched: best.item.vod_name, quality: best.quality });
          return [];
        }
        trace({
          event: 'matched',
          site: site.title,
          keyword: wanted.base,
          matched: best.item.vod_name,
          quality: best.quality,
          score: best.score,
          candidates: items.length
        });
        return resourcesFromItem(best.item, site.title, seriesTitle, type, parseApi, best.quality);
      } catch (error) {
        report(error);
        return [];
      }
    });

    var results = await Promise.all(tasks);
    var merged = dedupe(
      results.reduce(function (accumulator, current) {
        return accumulator.concat(current);
      }, [])
    );

    if (merged.length) {
      try {
        Widget.storage.set(cacheKey, merged, 10800);
      } catch (error) {
        /* 缓存写入失败不影响返回 */
      }
    }

    var filtered = filterByEpisode(merged, wantedEpisode, type);
    trace({
      event: 'done',
      at: new Date().toISOString(),
      title: seriesTitle,
      type: type,
      season: wanted.season,
      episode: wantedEpisode,
      sites: sites.length,
      collected: merged.length,
      returned: filtered.length,
      note: merged.length > 0 && filtered.length === 0 ? '有线路但被集数过滤掉了，可能是集号不匹配。' : undefined
    });
    return filtered;
  }

  // -------------------------------------------------------------------------
  // 导出
  // -------------------------------------------------------------------------

  return {
    // 主入口
    loadResources: loadResources,
    // 网络
    fetchPage: fetchPage,
    search: search,
    pickBest: pickBest,
    // 解析
    unwrap: unwrap,
    buildUrl: buildUrl,
    normalize: normalize,
    clean: clean,
    parseSeason: parseSeason,
    parseEpisode: parseEpisode,
    isDirectStream: isDirectStream,
    parseSites: parseSites,
    readTitle: readTitle,
    readType: readType,
    // 匹配
    scoreTitle: scoreTitle,
    matchQuality: matchQuality,
    collectLines: collectLines,
    toResource: toResource,
    resourcesFromItem: resourcesFromItem,
    dedupe: dedupe,
    filterByEpisode: filterByEpisode,
    // 常量
    DEFAULT_UA: DEFAULT_UA,
  };
})();
