// MissAV homepage/search widget for Forward
WidgetMetadata={id:"hyj1817.missav.home",title:"MissAV",icon:"https://missav.live/favicon.ico",version:"1.0.3",requiredVersion:"0.0.1",description:"MissAV 首页、分类、搜索与详情",author:"Forward Widgets",site:"https://missav.live",modules:[{id:"latest",title:"最近更新",functionName:"loadLatest",cacheDuration:600,params:[]},{id:"release",title:"新作上市",functionName:"loadRelease",cacheDuration:600,params:[]},{id:"uncensored",title:"无码流出",functionName:"loadUncensored",cacheDuration:600,params:[]},{id:"subtitle",title:"中文字幕",functionName:"loadSubtitle",cacheDuration:600,params:[]},{id:"actresses",title:"女优筛选",functionName:"loadActresses",cacheDuration:600,params:[{name:"cup",title:"罩杯",type:"input",value:"H"},{name:"age",title:"年龄",type:"input",value:"20-30"}]}],search:{title:"搜索",functionName:"search",params:[{name:"keyword",title:"关键词",type:"input"}]}};
var B="https://missav.live",U="Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1";
function tx(s){return String(s||"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim()}
function abs(u){u=String(u||"");if(u.indexOf("//")==0)return "https:"+u;if(u.indexOf("/")==0)return B+u;return u}
function parse(h){h=String(h||"");var a=[],re=/<a\b[^>]*href=["'](\/cn\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,m;while((m=re.exec(h))){var u=B+m[1].split(/[?#]/)[0],b=m[2],im=b.match(/<(?:img|video)\b[^>]*(?:data-src|src)=["']([^"']+)["']/i),al=b.match(/\balt=["']([^"']+)["']/i),t=tx(al?al[1]:b);if(!/^https:\/\/missav\.live\/cn\/[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/i.test(u)||t.length<2||a.some(function(x){return x.url===u}))continue;a.push({url:u,title:t,posterPath:im?abs(im[1]):"https://fourhoi.com/"+u.split("/").pop()+"/cover-t.jpg"})}return a}
async function list(path){try{var r=await Widget.http.get(B+path,{headers:{"User-Agent":U,Referer:B+"/cn"},timeout:15000});return parse(typeof r.data==="string"?r.data:(r.body||""))}catch(e){return[]}}
function out(a){return a.map(function(x){var slug=x.url.split("missav.live/")[1];return {id:"missav:"+slug,type:"url",title:x.title,seriesName:x.title,episodeName:x.title,description:x.title,mediaType:"movie",posterPath:x.posterPath,link:"missav:"+slug};})}
async function loadLatest(){return out(await list("/dm539/cn/new"))}async function loadRelease(){return out(await list("/dm635/cn/release"))}async function loadUncensored(){return out(await list("/dm817/cn/uncensored-leak"))}async function loadSubtitle(){return out(await list("/dm278/cn/chinese-subtitle"))}async function loadActresses(p){p=p||{};return out(await list("/cn/actresses?cup="+encodeURIComponent(p.cup||"H")+"&age="+encodeURIComponent(p.age||"20-30")))}async function search(p){return out(await list("/cn/search?query="+encodeURIComponent(p&&p.keyword||"")))}
