// MissAV homepage/search widget for Forward
WidgetMetadata={id:"hyj1817.missav.home",title:"MissAV",icon:"https://missav.live/favicon.ico",version:"1.0.2",requiredVersion:"0.0.1",description:"MissAV 首页、分类、搜索与详情",author:"Forward Widgets",site:"https://missav.live",modules:[{id:"latest",title:"最近更新",functionName:"loadLatest",cacheDuration:600,params:[]},{id:"release",title:"新作上市",functionName:"loadRelease",cacheDuration:600,params:[]},{id:"uncensored",title:"无码流出",functionName:"loadUncensored",cacheDuration:600,params:[]},{id:"subtitle",title:"中文字幕",functionName:"loadSubtitle",cacheDuration:600,params:[]},{id:"actresses",title:"女优筛选",functionName:"loadActresses",cacheDuration:600,params:[{name:"cup",title:"罩杯",type:"input",value:"H"},{name:"age",title:"年龄",type:"input",value:"20-30"}]}],search:{title:"搜索",functionName:"search",params:[{name:"keyword",title:"关键词",type:"input"}]}};
var B="https://missav.live",U="Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1";
function tx(s){return String(s||"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim()}
function abs(u){u=String(u||"");if(u.startsWith("//"))return "https:"+u;if(u.startsWith("/"))return B+u;return u}
function parse(h){let a=[],re=/<a\b[^>]*href=["'](\/cn\/[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)["'][^>]*>([\s\S]*?)<\/a>/gi,m;while(m=re.exec(h||"")){let u=B+m[1],block=m[2],img=block.match(/<(?:img|video)\b[^>]*(?:data-src|src)=["']([^"']+)["'][^>]*>/i),alt=block.match(/\balt=["']([^"']*)["']/i),t=tx(alt?alt[1]:block);if(!t||t.length<2||a.some(x=>x.url===u))continue;a.push({url:u,title:t,posterPath:img?abs(img[1]):""})}return a}
async function list(path){try{let r=await Widget.http.get(B+path,{headers:{"User-Agent":U,Referer:B+"/cn"},timeout:15000});return parse(typeof r?.data==="string"?r.data:r?.body)}catch(e){return[]}}
function out(a){return a.map(function(x){var slug=x.url.split("missav.live/")[1];return {id:"missav:"+slug,type:"url",title:x.title,seriesName:x.title,description:x.title,mediaType:"movie",posterPath:x.posterPath,link:"missav:"+slug};})}
async function loadLatest(){return out(await list("/dm539/cn/new"))}async function loadRelease(){return out(await list("/dm635/cn/release"))}async function loadUncensored(){return out(await list("/dm817/cn/uncensored-leak"))}async function loadSubtitle(){return out(await list("/dm278/cn/chinese-subtitle"))}async function loadActresses(p){p=p||{};return out(await list("/cn/actresses?cup="+encodeURIComponent(p.cup||"H")+"&age="+encodeURIComponent(p.age||"20-30")))}async function search(p){return out(await list("/cn/search?query="+encodeURIComponent(p?.keyword||"")))}
