"use strict";
/**
 * 把 lib/maccms.js 内联进各入口层，生成 widgets/ 下的单文件组件。
 * ---------------------------------------------------------------------------
 * Forward 的组件是单文件脚本，没有模块系统，因此共享逻辑只能构建期内联。
 * 本脚本是唯一的生成入口，生成物顶部带 "Do not edit directly" 标记。
 *
 * 用法：node scripts/build-maccms.js
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");
const LIB = path.join(ROOT, "lib", "maccms.js");

const TARGETS = [
  { entry: path.join(ROOT, "lib", "entries", "maccms-source.js"), output: path.join(ROOT, "widgets", "maccms-source.js") },
  { entry: path.join(ROOT, "lib", "entries", "fw-sourcecheck.js"), output: path.join(ROOT, "widgets", "fw-sourcecheck.js") },
];

const BANNER = "/* Generated by scripts/build-maccms.js from lib/maccms.js. Do not edit directly. */";

function vmContext() {
  return {
    console: { log() {}, error() {}, warn() {} },
    URL,
    Date,
    JSON,
    Math,
    Object,
    Array,
    String,
    Number,
    RegExp,
    Promise,
    encodeURIComponent,
    decodeURIComponent,
    setTimeout,
    clearTimeout,
    Uint8Array,
    DataView,
    ArrayBuffer,
    WebAssembly,
    Widget: { http: {}, storage: null, sharedCache: null },
  };
}

function build(libSource) {
  const results = [];
  for (const target of TARGETS) {
    const entry = fs.readFileSync(target.entry, "utf8");
    const output = [BANNER, entry.trim(), "", libSource.trim(), ""].join("\n");

    // 构建期验证：语法与 WidgetMetadata 必须可解析
    const context = vmContext();
    vm.createContext(context);
    vm.runInContext(output, context, { filename: target.output });

    const metadata = context.WidgetMetadata;
    if (!metadata || !metadata.id || !metadata.title) {
      throw new Error(`生成物缺少有效 WidgetMetadata: ${path.basename(target.output)}`);
    }
    if (typeof context.loadResource !== "function") {
      throw new Error(`生成物缺少 loadResource: ${path.basename(target.output)}`);
    }
    if (typeof context.Maccms !== "object") {
      throw new Error(`适配层未内联成功: ${path.basename(target.output)}`);
    }

    const temporary = `${target.output}.tmp`;
    fs.writeFileSync(temporary, output, "utf8");
    fs.rmSync(target.output, { force: true });
    fs.renameSync(temporary, target.output);

    results.push({ file: path.relative(ROOT, target.output), id: metadata.id, bytes: Buffer.byteLength(output) });
  }
  return results;
}

function main() {
  if (!fs.existsSync(LIB)) throw new Error(`找不到适配层：${LIB}`);
  const libSource = fs.readFileSync(LIB, "utf8");
  const results = build(libSource);
  for (const result of results) {
    console.log(`generated ${result.file}  (${result.id}, ${result.bytes} bytes)`);
  }
  console.log(`done: ${results.length} widget(s)`);
}

main();
